-- MySQL Script generated by MySQL Workbench
-- lun 15 feb 2016 02:21:18 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema arieldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema arieldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `arieldb` DEFAULT CHARACTER SET latin1 ;
USE `arieldb` ;

-- -----------------------------------------------------
-- Table `arieldb`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arieldb`.`PRODUCT` (
  `ID` INT(11) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `arieldb`.`WORK_ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arieldb`.`WORK_ORDER` (
  `ID` INT(11) NOT NULL,
  `YEAR` INT(11) NOT NULL,
  `PRODUCT_ID` INT(11) NOT NULL,
  `AMOUNT` DECIMAL(10,0) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `URGENT` TINYINT(1) NULL DEFAULT NULL,
  `STATUS` VARCHAR(255) NULL DEFAULT NULL,
  `DATE_CREATE` VARCHAR(45) NOT NULL,
  `DATE_FINISH` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`, `YEAR`),
  INDEX `PRODUCT_FK` (`PRODUCT_ID` ASC),
  CONSTRAINT `PRODUCT_FK`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `arieldb`.`PRODUCT` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `arieldb`.`ASSIGNED_TASK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arieldb`.`ASSIGNED_TASK` (
  `ID` INT(11) NOT NULL,
  `WORK_ORDER_ID` INT(11) NOT NULL,
  `WORK_ORDER_YEAR` INT(11) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL,
  `IN_EXECUTION` VARCHAR(45) NULL DEFAULT NULL,
  `DATE_FINISH` VARCHAR(45) NULL DEFAULT NULL,
  `WORKER_ID` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `WORK_ORDER_YEAR_ASSIGNED_TASK_idx` (`WORK_ORDER_YEAR` ASC),
  INDEX `WORK_ORDER_ID_ASSIGNED_TASK_idx` (`WORK_ORDER_ID` ASC, `WORK_ORDER_YEAR` ASC),
  CONSTRAINT `WORK_ORDER_ID_ASSIGNED_TASK`
    FOREIGN KEY (`WORK_ORDER_ID` , `WORK_ORDER_YEAR`)
    REFERENCES `arieldb`.`WORK_ORDER` (`ID` , `YEAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `arieldb`.`FEEDSTOCK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arieldb`.`FEEDSTOCK` (
  `ID` INT(11) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `AMOUNT_STOCK` DECIMAL(10,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `arieldb`.`FEEDSTOCK_DETAIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arieldb`.`FEEDSTOCK_DETAIL` (
  `ID` INT(11) NOT NULL,
  `FEEDSTOCK_ID` INT(11) NOT NULL,
  `TASK_ID` INT(11) NOT NULL,
  `AMOUNT` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FEEDSTOCK_FK_idx` (`FEEDSTOCK_ID` ASC),
  INDEX `TASK_FK_idx` (`TASK_ID` ASC),
  CONSTRAINT `FEEDSTOCK_FK`
    FOREIGN KEY (`FEEDSTOCK_ID`)
    REFERENCES `arieldb`.`FEEDSTOCK` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TASK_FK`
    FOREIGN KEY (`TASK_ID`)
    REFERENCES `arieldb`.`ASSIGNED_TASK` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `arieldb`.`WORKER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arieldb`.`WORKER` (
  `ID` INT(11) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
